version: '3'
services:
  passenger-service:
    build: ./passenger-service
    ports:
      - "9090:9090"
    depends_on:
      - kafka
      - mongodb
  transport-service:
    build: ./transport-service
    ports:
      - "9091:9091"
    depends_on:
      - kafka
  ticketing-service:
    build: ./ticketing-service
    ports:
      - "9092:9092"
    depends_on:
      - kafka
      - mongodb
  payment-service:
    build: ./payment-service
    ports:
      - "9093:9093"
    depends_on:
      - kafka
  notification-service:
    build: ./notification-service
    ports:
      - "9094:9094"
    depends_on:
      - kafka
  admin-service:
    build: ./admin-service
    ports:
      - "9095:9095"
    depends_on:
      - mongodb
  kafka:
    image: confluentinc/cp-kafka
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper
  zookeeper:
    image: confluentinc/cp-zookeeper
  mongodb:
    image: mongo