[package]
org = "windhoektransit"
name = "passenger_service"
version = "1.0.0"

[[dependency]]
org = "ballerinax"
name = "kafka"
version = "4.2.0"

[[dependency]]
org = "ballerinax"
name = "mongodb"
version = "1.7.0"