[package]
org = "administrator"
name = "transport_service"
version = "0.1.0"
distribution = "2201.12.9"

[[dependency]]
org = "ballerinax"
name = "kafka"
version = "3.6.0"  # Or the version added, e.g., "3.0.0"

[[dependency]]
org = "ballerinax"
name = "mongodb"
version = "2.1.0"  # Or the version added

[build-options]
cloud = "docker"
observabilityIncluded = true
