[package]
org = "administrator"
name = "payment_service"
version = "0.1.0"
distribution = "2201.12.9"

[[dependency]]
org = "ballerinax"
name = "kafka"
version = "latest"  # Or the version added, e.g., "3.0.0"

[[dependency]]
org = "ballerinax"
name = "mongodb"
version = "latest"  # Or the version added

[build-options]
cloud = "docker"


